black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 156
  - 114
  min:
  - 0
  - 131
  - 0
green:
  max:
  - 255
  - 110
  - 255
  min:
  - 47
  - 0
  - 135
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 153
  - 135
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
